-- Run this once in Supabase: SQL Editor -> New query -> Paste -> Run

create table if not exists expenses (
  id bigint generated by default as identity primary key,
  date text not null,
  item_name text not null,
  category text not null,
  ai_price double precision not null,
  actual_price double precision not null,
  is_modified integer not null default 0
);

create table if not exists budget_requests (
  id bigint generated by default as identity primary key,
  date text not null,
  amount double precision not null,
  type text not null,
  status text not null default 'Pending',
  reason text default ''
);

-- Optional: disable RLS for simple family apps using service_role key in Streamlit secrets.
-- If you use the anon key instead, add policies in Supabase dashboard.

alter table expenses enable row level security;
alter table budget_requests enable row level security;

create policy "expenses_all_access"
  on expenses for all
  using (true)
  with check (true);

create policy "budget_requests_all_access"
  on budget_requests for all
  using (true)
  with check (true);
